development: &default
  adapter: postgresql
  encoding: utf8
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  database: <%= ENV['DB_NAME'] || 'pickeatapp_dev' %>

test:
  <<: *default
  database: pickeatappdev_test

production:
  <<: *default
